name: sync-ftp
on:
  workflow_dispatch:

jobs:
  sync-ftp-files:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "update the PHP files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -type f -name "*.php" | while read file; do
              # Get the relative path
              remote_path="/aowow//${file#./}"
              
              remote_dir=$(dirname "$remote_path")
              echo "$file"
              echo "ftp://wowgaming@ftp.wowgaming.altervista.org/$remote_path"
              # curl --user wowgaming:${{ secrets.FTP_PASSWORD }} --upload-file "$file" "ftp://wowgaming@ftp.wowgaming.altervista.org/$remote_path"
          done
